[package]
name = "file-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
memmap2 = "0.9.5"
parse-size = "1.1.0"
rand = "0.9.0"
tempfile = "3.19.1"

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "read"
harness = false
