[package]
name = "file-bench"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
memmap2 = "0.9.5"
tempfile = "3.19.1"

[[bench]]
name = "read"
harness = false
